# Generated by Django 5.1.6 on 2025-07-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_verificationcode_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationcode',
            old_name='is_approved',
            new_name='is_used',
        ),
    ]
