# Generated by Django 5.1.6 on 2025-07-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="progress",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
