# Generated by Django 5.1.6 on 2025-08-03 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_courseprogress_lessonprogress_moduleprogress"),
        ("enrollments", "0002_enrollment_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="courses.course",
            ),
        ),
    ]
