# Generated by Django 5.1.6 on 2025-07-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_moduleassessment"),
        ("categories", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
            ),
        ),
        migrations.DeleteModel(
            name="TestAssessment",
        ),
    ]
