# Generated by Django 5.1.6 on 2025-07-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_question_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
