# Generated by Django 5.1.6 on 2025-07-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0007_alter_question_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={
                ("order", "course_assessment"),
                ("order", "module_assessment"),
            },
        ),
    ]
