# Generated by Django 5.1.6 on 2025-07-17 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0010_question_is_true"),
        ("courses", "0002_alter_module_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleassessment",
            name="module",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="courses.module"
            ),
        ),
    ]
