# Generated by Django 5.1.6 on 2025-07-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0011_alter_moduleassessment_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="is_true",
            field=models.BooleanField(),
        ),
    ]
