# Generated by Django 5.1.6 on 2025-07-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0012_alter_question_is_true"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="is_true",
            field=models.BooleanField(default=False),
        ),
    ]
