# Generated by Django 5.1.6 on 2025-07-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0016_question_correct_answer_question_is_true_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_true',
            field=models.BooleanField(),
        ),
    ]
