# Generated by Django 5.1.6 on 2025-07-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0019_alter_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
