# Generated by Django 5.1.6 on 2025-07-29 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0023_testblueprint_testsession_testsessionquestion_and_more"),
        ("categories", "0002_alter_category_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCategoryDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
            ],
        ),
    ]
