# Generated by Django 5.1.6 on 2025-07-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0024_testcategorydescription"),
        ("categories", "0002_alter_category_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TestCategoryDescription",
            new_name="TestAssessmentCategoryDescription",
        ),
    ]
