# Generated by Django 5.1.6 on 2025-07-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0025_rename_testcategorydescription_testassessmentcategorydescription",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testassessment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="testblueprint",
            name="difficulty",
            field=models.CharField(
                choices=[("EASY", "Easy"), ("NORMAL", "Normal"), ("HARD", "Hard")],
                default="EASY",
                max_length=6,
            ),
        ),
        migrations.RemoveField(
            model_name="testassessment",
            name="difficulty",
        ),
    ]
