# Generated by Django 5.1.6 on 2025-07-31 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0026_alter_testassessment_unique_together_and_more"),
        ("categories", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="testblueprint",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="testassessment",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="categories.category"
            ),
        ),
    ]
