# Generated by Django 5.1.6 on 2025-07-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0027_testblueprint_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsession",
            name="status",
            field=models.CharField(
                choices=[("IP", "In Progress"), ("S", "Submitted"), ("ERR", "Error")],
                default="IP",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="testsessionquestion",
            name="snapshot_options",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
