# Generated by Django 5.1.6 on 2025-08-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0031_alter_testsessionquestion_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testsession",
            old_name="is_submitted",
            new_name="is_marked",
        ),
    ]
