# Generated by Django 5.1.6 on 2025-08-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0034_remove_testsession_total_score_testsession_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testassessment',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testassessment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
