# Generated by Django 5.1.6 on 2025-08-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0035_testassessment_description_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestAssessmentCategoryDescription",
        ),
    ]
