# Generated by Django 5.1.6 on 2025-08-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0036_delete_testassessmentcategorydescription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testsession",
            name="duration_minutes",
        ),
    ]
