# Generated by Django 5.1.6 on 2025-08-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0037_remove_testsession_duration_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testassessment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
