# Generated by Django 5.1.6 on 2025-08-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0041_assessmentquestion_assessmentanswer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessmentanswer",
            name="assessment_question",
        ),
        migrations.AddField(
            model_name="assessmentanswer",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="assessments.question",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessmentanswer",
            name="session",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="assessments.assessmentsession",
            ),
            preserve_default=False,
        ),
    ]
