# Generated by Django 5.1.6 on 2025-08-09 16:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0042_remove_assessmentanswer_assessment_question_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assessmentsession",
            unique_together={("user", "content_type", "object_id")},
        ),
    ]
