# Generated by Django 5.2.4 on 2025-09-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="certificate_file",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
