# Generated by Django 5.1.6 on 2025-07-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('order', 'course')},
        ),
    ]
