# Generated by Django 5.1.6 on 2025-08-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_courseprogress_lessonprogress_moduleprogress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseprogress",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="lessonprogress",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="moduleprogress",
            name="is_completed",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.module",
            ),
        ),
    ]
