# Generated by Django 5.1.6 on 2025-08-06 20:00

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_lesson_content_lesson_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseprogress",
            name="last_accessed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="last_accessed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moduleprogress",
            name="last_accessed_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 6, 20, 0, 0, 903300, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
