# Generated by Django 5.1.6 on 2025-08-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_courseprogress_last_accessed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
