# Generated by Django 5.1.6 on 2025-08-07 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_alter_courseprogress_last_accessed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleprogress",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.module"
            ),
        ),
    ]
