# Generated by Django 5.1.6 on 2025-08-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_courseprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together=set(),
        ),
    ]
