# Generated by Django 5.1.6 on 2025-08-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_lessonprogress_unique_together_and_more'),
        ('enrollments', '0003_alter_enrollment_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('enrollment', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('enrollment', 'module')},
        ),
    ]
