# Generated by Django 5.1.6 on 2025-08-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_courseprogress_last_accessed_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
