# Generated by Django 5.1.6 on 2025-08-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_remove_lesson_video_url_lesson_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseprogress",
            name="progress",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="progress",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="moduleprogress",
            name="progress",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
