# Generated by Django 5.1.6 on 2025-08-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_courseprogress_progress_lessonprogress_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonvideo',
            name='lesson',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module__order', 'order']},
        ),
        migrations.DeleteModel(
            name='LessonArticle',
        ),
        migrations.DeleteModel(
            name='LessonVideo',
        ),
    ]
