# Generated by Django 5.1.6 on 2025-08-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_lessonvideo_lesson_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('order', 'course')},
        ),
    ]
