# Generated by Django 5.2.4 on 2025-09-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0022_alter_module_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
