# Generated by Django 5.2.4 on 2025-09-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0023_alter_lesson_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="draft_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=15,
            ),
        ),
    ]
