# Generated by Django 5.2.4 on 2025-09-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0024_lesson_draft_content_lesson_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
