# Generated by Django 5.2.4 on 2025-09-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0025_lesson_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="course",
            name="enrollment_count",
        ),
        migrations.RemoveField(
            model_name="course",
            name="rating_count",
        ),
    ]
