# Generated by Django 5.2.4 on 2025-07-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_sub',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_seen',
        ),
    ]
